// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: command.proto

package proto.common;

public interface CommandsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chxy.proto.common.Commands)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .chxy.proto.common.Command commands = 1;</code>
   */
  java.util.List<proto.common.Command> 
      getCommandsList();
  /**
   * <code>repeated .chxy.proto.common.Command commands = 1;</code>
   */
  proto.common.Command getCommands(int index);
  /**
   * <code>repeated .chxy.proto.common.Command commands = 1;</code>
   */
  int getCommandsCount();
  /**
   * <code>repeated .chxy.proto.common.Command commands = 1;</code>
   */
  java.util.List<? extends proto.common.CommandOrBuilder> 
      getCommandsOrBuilderList();
  /**
   * <code>repeated .chxy.proto.common.Command commands = 1;</code>
   */
  proto.common.CommandOrBuilder getCommandsOrBuilder(
      int index);
}
