// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: command.proto

package proto.common;

public final class CommandOuterClass {
  private CommandOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chxy_proto_common_KeyStringValuePair_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chxy_proto_common_KeyStringValuePair_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chxy_proto_common_Commands_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chxy_proto_common_Commands_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chxy_proto_common_Command_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chxy_proto_common_Command_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcommand.proto\022\021chxy.proto.common\"0\n\022Ke" +
      "yStringValuePair\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002" +
      " \001(\t\"8\n\010Commands\022,\n\010commands\030\001 \003(\0132\032.chx" +
      "y.proto.common.Command\"O\n\007Command\022\017\n\007com" +
      "mand\030\001 \001(\t\0223\n\004args\030\002 \003(\0132%.chxy.proto.co" +
      "mmon.KeyStringValuePairB\020\n\014proto.commonP" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_chxy_proto_common_KeyStringValuePair_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_chxy_proto_common_KeyStringValuePair_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chxy_proto_common_KeyStringValuePair_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_chxy_proto_common_Commands_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_chxy_proto_common_Commands_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chxy_proto_common_Commands_descriptor,
        new java.lang.String[] { "Commands", });
    internal_static_chxy_proto_common_Command_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_chxy_proto_common_Command_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chxy_proto_common_Command_descriptor,
        new java.lang.String[] { "Command", "Args", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
