// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: command.proto

package proto.common;

public interface CommandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chxy.proto.common.Command)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string command = 1;</code>
   */
  java.lang.String getCommand();
  /**
   * <code>string command = 1;</code>
   */
  com.google.protobuf.ByteString
      getCommandBytes();

  /**
   * <code>repeated .chxy.proto.common.KeyStringValuePair args = 2;</code>
   */
  java.util.List<proto.common.KeyStringValuePair> 
      getArgsList();
  /**
   * <code>repeated .chxy.proto.common.KeyStringValuePair args = 2;</code>
   */
  proto.common.KeyStringValuePair getArgs(int index);
  /**
   * <code>repeated .chxy.proto.common.KeyStringValuePair args = 2;</code>
   */
  int getArgsCount();
  /**
   * <code>repeated .chxy.proto.common.KeyStringValuePair args = 2;</code>
   */
  java.util.List<? extends proto.common.KeyStringValuePairOrBuilder> 
      getArgsOrBuilderList();
  /**
   * <code>repeated .chxy.proto.common.KeyStringValuePair args = 2;</code>
   */
  proto.common.KeyStringValuePairOrBuilder getArgsOrBuilder(
      int index);
}
