// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: report.proto

package proto.common;

public final class Report {
  private Report() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chxy_proto_common_ReportData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chxy_proto_common_ReportData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014report.proto\022\021chxy.proto.common\032\rcomma" +
      "nd.proto\"v\n\nReportData\0221\n\nreportType\030\001 \001" +
      "(\0162\035.chxy.proto.common.ReportType\0225\n\006det" +
      "ail\030\002 \003(\0132%.chxy.proto.common.KeyStringV" +
      "aluePair*#\n\nReportType\022\n\n\006Normal\020\000\022\t\n\005Er" +
      "ror\020\0012\263\001\n\rReportService\022L\n\014uploadReport\022" +
      "\035.chxy.proto.common.ReportData\032\033.chxy.pr" +
      "oto.common.Commands\"\000\022T\n\022uploadStreamRep" +
      "ort\022\035.chxy.proto.common.ReportData\032\033.chx" +
      "y.proto.common.Commands\"\000(\001B\020\n\014proto.com" +
      "monP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          proto.common.CommandOuterClass.getDescriptor(),
        }, assigner);
    internal_static_chxy_proto_common_ReportData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_chxy_proto_common_ReportData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chxy_proto_common_ReportData_descriptor,
        new java.lang.String[] { "ReportType", "Detail", });
    proto.common.CommandOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
