// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: report.proto

package proto.common;

public interface ReportDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chxy.proto.common.ReportData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.chxy.proto.common.ReportType reportType = 1;</code>
   */
  int getReportTypeValue();
  /**
   * <code>.chxy.proto.common.ReportType reportType = 1;</code>
   */
  proto.common.ReportType getReportType();

  /**
   * <code>repeated .chxy.proto.common.KeyStringValuePair detail = 2;</code>
   */
  java.util.List<proto.common.KeyStringValuePair> 
      getDetailList();
  /**
   * <code>repeated .chxy.proto.common.KeyStringValuePair detail = 2;</code>
   */
  proto.common.KeyStringValuePair getDetail(int index);
  /**
   * <code>repeated .chxy.proto.common.KeyStringValuePair detail = 2;</code>
   */
  int getDetailCount();
  /**
   * <code>repeated .chxy.proto.common.KeyStringValuePair detail = 2;</code>
   */
  java.util.List<? extends proto.common.KeyStringValuePairOrBuilder> 
      getDetailOrBuilderList();
  /**
   * <code>repeated .chxy.proto.common.KeyStringValuePair detail = 2;</code>
   */
  proto.common.KeyStringValuePairOrBuilder getDetailOrBuilder(
      int index);
}
