// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.proto.common;

public interface CommandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:common.Command)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string command = 1;</code>
   */
  java.lang.String getCommand();
  /**
   * <code>string command = 1;</code>
   */
  com.google.protobuf.ByteString
      getCommandBytes();

  /**
   * <code>repeated .common.KeyStringValuePair args = 2;</code>
   */
  java.util.List<com.proto.common.KeyStringValuePair> 
      getArgsList();
  /**
   * <code>repeated .common.KeyStringValuePair args = 2;</code>
   */
  com.proto.common.KeyStringValuePair getArgs(int index);
  /**
   * <code>repeated .common.KeyStringValuePair args = 2;</code>
   */
  int getArgsCount();
  /**
   * <code>repeated .common.KeyStringValuePair args = 2;</code>
   */
  java.util.List<? extends com.proto.common.KeyStringValuePairOrBuilder> 
      getArgsOrBuilderList();
  /**
   * <code>repeated .common.KeyStringValuePair args = 2;</code>
   */
  com.proto.common.KeyStringValuePairOrBuilder getArgsOrBuilder(
      int index);
}
