// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.proto.common;

public interface CommandsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:common.Commands)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .common.Command commands = 1;</code>
   */
  java.util.List<com.proto.common.Command> 
      getCommandsList();
  /**
   * <code>repeated .common.Command commands = 1;</code>
   */
  com.proto.common.Command getCommands(int index);
  /**
   * <code>repeated .common.Command commands = 1;</code>
   */
  int getCommandsCount();
  /**
   * <code>repeated .common.Command commands = 1;</code>
   */
  java.util.List<? extends com.proto.common.CommandOrBuilder> 
      getCommandsOrBuilderList();
  /**
   * <code>repeated .common.Command commands = 1;</code>
   */
  com.proto.common.CommandOrBuilder getCommandsOrBuilder(
      int index);
}
