// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.proto.common;

public interface KeyStringValuePairOrBuilder extends
    // @@protoc_insertion_point(interface_extends:common.KeyStringValuePair)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key = 1;</code>
   */
  java.lang.String getKey();
  /**
   * <code>string key = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>string value = 2;</code>
   */
  java.lang.String getValue();
  /**
   * <code>string value = 2;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
