// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: report.proto

package com.proto.report;

public interface ReportDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:report.ReportData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.report.ReportType reportType = 1;</code>
   */
  int getReportTypeValue();
  /**
   * <code>.report.ReportType reportType = 1;</code>
   */
  com.proto.report.ReportType getReportType();

  /**
   * <code>repeated .common.KeyStringValuePair detail = 2;</code>
   */
  java.util.List<com.proto.common.KeyStringValuePair> 
      getDetailList();
  /**
   * <code>repeated .common.KeyStringValuePair detail = 2;</code>
   */
  com.proto.common.KeyStringValuePair getDetail(int index);
  /**
   * <code>repeated .common.KeyStringValuePair detail = 2;</code>
   */
  int getDetailCount();
  /**
   * <code>repeated .common.KeyStringValuePair detail = 2;</code>
   */
  java.util.List<? extends com.proto.common.KeyStringValuePairOrBuilder> 
      getDetailOrBuilderList();
  /**
   * <code>repeated .common.KeyStringValuePair detail = 2;</code>
   */
  com.proto.common.KeyStringValuePairOrBuilder getDetailOrBuilder(
      int index);
}
