// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: report.proto

package com.proto.report;

/**
 * Protobuf type {@code report.ReportData}
 */
public  final class ReportData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:report.ReportData)
    ReportDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReportData.newBuilder() to construct.
  private ReportData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReportData() {
    reportType_ = 0;
    detail_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ReportData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            reportType_ = rawValue;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              detail_ = new java.util.ArrayList<com.proto.common.KeyStringValuePair>();
              mutable_bitField0_ |= 0x00000002;
            }
            detail_.add(
                input.readMessage(com.proto.common.KeyStringValuePair.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        detail_ = java.util.Collections.unmodifiableList(detail_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.proto.report.Report.internal_static_report_ReportData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.proto.report.Report.internal_static_report_ReportData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.proto.report.ReportData.class, com.proto.report.ReportData.Builder.class);
  }

  private int bitField0_;
  public static final int REPORTTYPE_FIELD_NUMBER = 1;
  private int reportType_;
  /**
   * <code>.report.ReportType reportType = 1;</code>
   */
  public int getReportTypeValue() {
    return reportType_;
  }
  /**
   * <code>.report.ReportType reportType = 1;</code>
   */
  public com.proto.report.ReportType getReportType() {
    @SuppressWarnings("deprecation")
    com.proto.report.ReportType result = com.proto.report.ReportType.valueOf(reportType_);
    return result == null ? com.proto.report.ReportType.UNRECOGNIZED : result;
  }

  public static final int DETAIL_FIELD_NUMBER = 2;
  private java.util.List<com.proto.common.KeyStringValuePair> detail_;
  /**
   * <code>repeated .common.KeyStringValuePair detail = 2;</code>
   */
  public java.util.List<com.proto.common.KeyStringValuePair> getDetailList() {
    return detail_;
  }
  /**
   * <code>repeated .common.KeyStringValuePair detail = 2;</code>
   */
  public java.util.List<? extends com.proto.common.KeyStringValuePairOrBuilder> 
      getDetailOrBuilderList() {
    return detail_;
  }
  /**
   * <code>repeated .common.KeyStringValuePair detail = 2;</code>
   */
  public int getDetailCount() {
    return detail_.size();
  }
  /**
   * <code>repeated .common.KeyStringValuePair detail = 2;</code>
   */
  public com.proto.common.KeyStringValuePair getDetail(int index) {
    return detail_.get(index);
  }
  /**
   * <code>repeated .common.KeyStringValuePair detail = 2;</code>
   */
  public com.proto.common.KeyStringValuePairOrBuilder getDetailOrBuilder(
      int index) {
    return detail_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (reportType_ != com.proto.report.ReportType.Normal.getNumber()) {
      output.writeEnum(1, reportType_);
    }
    for (int i = 0; i < detail_.size(); i++) {
      output.writeMessage(2, detail_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (reportType_ != com.proto.report.ReportType.Normal.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, reportType_);
    }
    for (int i = 0; i < detail_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, detail_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.proto.report.ReportData)) {
      return super.equals(obj);
    }
    com.proto.report.ReportData other = (com.proto.report.ReportData) obj;

    boolean result = true;
    result = result && reportType_ == other.reportType_;
    result = result && getDetailList()
        .equals(other.getDetailList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REPORTTYPE_FIELD_NUMBER;
    hash = (53 * hash) + reportType_;
    if (getDetailCount() > 0) {
      hash = (37 * hash) + DETAIL_FIELD_NUMBER;
      hash = (53 * hash) + getDetailList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.proto.report.ReportData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.proto.report.ReportData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.proto.report.ReportData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.proto.report.ReportData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.proto.report.ReportData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.proto.report.ReportData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.proto.report.ReportData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.proto.report.ReportData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.proto.report.ReportData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.proto.report.ReportData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.proto.report.ReportData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.proto.report.ReportData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.proto.report.ReportData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code report.ReportData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:report.ReportData)
      com.proto.report.ReportDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.proto.report.Report.internal_static_report_ReportData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.proto.report.Report.internal_static_report_ReportData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.proto.report.ReportData.class, com.proto.report.ReportData.Builder.class);
    }

    // Construct using com.proto.report.ReportData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDetailFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      reportType_ = 0;

      if (detailBuilder_ == null) {
        detail_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        detailBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.proto.report.Report.internal_static_report_ReportData_descriptor;
    }

    @java.lang.Override
    public com.proto.report.ReportData getDefaultInstanceForType() {
      return com.proto.report.ReportData.getDefaultInstance();
    }

    @java.lang.Override
    public com.proto.report.ReportData build() {
      com.proto.report.ReportData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.proto.report.ReportData buildPartial() {
      com.proto.report.ReportData result = new com.proto.report.ReportData(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.reportType_ = reportType_;
      if (detailBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          detail_ = java.util.Collections.unmodifiableList(detail_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.detail_ = detail_;
      } else {
        result.detail_ = detailBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.proto.report.ReportData) {
        return mergeFrom((com.proto.report.ReportData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.proto.report.ReportData other) {
      if (other == com.proto.report.ReportData.getDefaultInstance()) return this;
      if (other.reportType_ != 0) {
        setReportTypeValue(other.getReportTypeValue());
      }
      if (detailBuilder_ == null) {
        if (!other.detail_.isEmpty()) {
          if (detail_.isEmpty()) {
            detail_ = other.detail_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureDetailIsMutable();
            detail_.addAll(other.detail_);
          }
          onChanged();
        }
      } else {
        if (!other.detail_.isEmpty()) {
          if (detailBuilder_.isEmpty()) {
            detailBuilder_.dispose();
            detailBuilder_ = null;
            detail_ = other.detail_;
            bitField0_ = (bitField0_ & ~0x00000002);
            detailBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDetailFieldBuilder() : null;
          } else {
            detailBuilder_.addAllMessages(other.detail_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.proto.report.ReportData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.proto.report.ReportData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int reportType_ = 0;
    /**
     * <code>.report.ReportType reportType = 1;</code>
     */
    public int getReportTypeValue() {
      return reportType_;
    }
    /**
     * <code>.report.ReportType reportType = 1;</code>
     */
    public Builder setReportTypeValue(int value) {
      reportType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.report.ReportType reportType = 1;</code>
     */
    public com.proto.report.ReportType getReportType() {
      @SuppressWarnings("deprecation")
      com.proto.report.ReportType result = com.proto.report.ReportType.valueOf(reportType_);
      return result == null ? com.proto.report.ReportType.UNRECOGNIZED : result;
    }
    /**
     * <code>.report.ReportType reportType = 1;</code>
     */
    public Builder setReportType(com.proto.report.ReportType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      reportType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.report.ReportType reportType = 1;</code>
     */
    public Builder clearReportType() {
      
      reportType_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.proto.common.KeyStringValuePair> detail_ =
      java.util.Collections.emptyList();
    private void ensureDetailIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        detail_ = new java.util.ArrayList<com.proto.common.KeyStringValuePair>(detail_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.proto.common.KeyStringValuePair, com.proto.common.KeyStringValuePair.Builder, com.proto.common.KeyStringValuePairOrBuilder> detailBuilder_;

    /**
     * <code>repeated .common.KeyStringValuePair detail = 2;</code>
     */
    public java.util.List<com.proto.common.KeyStringValuePair> getDetailList() {
      if (detailBuilder_ == null) {
        return java.util.Collections.unmodifiableList(detail_);
      } else {
        return detailBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .common.KeyStringValuePair detail = 2;</code>
     */
    public int getDetailCount() {
      if (detailBuilder_ == null) {
        return detail_.size();
      } else {
        return detailBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .common.KeyStringValuePair detail = 2;</code>
     */
    public com.proto.common.KeyStringValuePair getDetail(int index) {
      if (detailBuilder_ == null) {
        return detail_.get(index);
      } else {
        return detailBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .common.KeyStringValuePair detail = 2;</code>
     */
    public Builder setDetail(
        int index, com.proto.common.KeyStringValuePair value) {
      if (detailBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDetailIsMutable();
        detail_.set(index, value);
        onChanged();
      } else {
        detailBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .common.KeyStringValuePair detail = 2;</code>
     */
    public Builder setDetail(
        int index, com.proto.common.KeyStringValuePair.Builder builderForValue) {
      if (detailBuilder_ == null) {
        ensureDetailIsMutable();
        detail_.set(index, builderForValue.build());
        onChanged();
      } else {
        detailBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .common.KeyStringValuePair detail = 2;</code>
     */
    public Builder addDetail(com.proto.common.KeyStringValuePair value) {
      if (detailBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDetailIsMutable();
        detail_.add(value);
        onChanged();
      } else {
        detailBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .common.KeyStringValuePair detail = 2;</code>
     */
    public Builder addDetail(
        int index, com.proto.common.KeyStringValuePair value) {
      if (detailBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDetailIsMutable();
        detail_.add(index, value);
        onChanged();
      } else {
        detailBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .common.KeyStringValuePair detail = 2;</code>
     */
    public Builder addDetail(
        com.proto.common.KeyStringValuePair.Builder builderForValue) {
      if (detailBuilder_ == null) {
        ensureDetailIsMutable();
        detail_.add(builderForValue.build());
        onChanged();
      } else {
        detailBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .common.KeyStringValuePair detail = 2;</code>
     */
    public Builder addDetail(
        int index, com.proto.common.KeyStringValuePair.Builder builderForValue) {
      if (detailBuilder_ == null) {
        ensureDetailIsMutable();
        detail_.add(index, builderForValue.build());
        onChanged();
      } else {
        detailBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .common.KeyStringValuePair detail = 2;</code>
     */
    public Builder addAllDetail(
        java.lang.Iterable<? extends com.proto.common.KeyStringValuePair> values) {
      if (detailBuilder_ == null) {
        ensureDetailIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, detail_);
        onChanged();
      } else {
        detailBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .common.KeyStringValuePair detail = 2;</code>
     */
    public Builder clearDetail() {
      if (detailBuilder_ == null) {
        detail_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        detailBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .common.KeyStringValuePair detail = 2;</code>
     */
    public Builder removeDetail(int index) {
      if (detailBuilder_ == null) {
        ensureDetailIsMutable();
        detail_.remove(index);
        onChanged();
      } else {
        detailBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .common.KeyStringValuePair detail = 2;</code>
     */
    public com.proto.common.KeyStringValuePair.Builder getDetailBuilder(
        int index) {
      return getDetailFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .common.KeyStringValuePair detail = 2;</code>
     */
    public com.proto.common.KeyStringValuePairOrBuilder getDetailOrBuilder(
        int index) {
      if (detailBuilder_ == null) {
        return detail_.get(index);  } else {
        return detailBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .common.KeyStringValuePair detail = 2;</code>
     */
    public java.util.List<? extends com.proto.common.KeyStringValuePairOrBuilder> 
         getDetailOrBuilderList() {
      if (detailBuilder_ != null) {
        return detailBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(detail_);
      }
    }
    /**
     * <code>repeated .common.KeyStringValuePair detail = 2;</code>
     */
    public com.proto.common.KeyStringValuePair.Builder addDetailBuilder() {
      return getDetailFieldBuilder().addBuilder(
          com.proto.common.KeyStringValuePair.getDefaultInstance());
    }
    /**
     * <code>repeated .common.KeyStringValuePair detail = 2;</code>
     */
    public com.proto.common.KeyStringValuePair.Builder addDetailBuilder(
        int index) {
      return getDetailFieldBuilder().addBuilder(
          index, com.proto.common.KeyStringValuePair.getDefaultInstance());
    }
    /**
     * <code>repeated .common.KeyStringValuePair detail = 2;</code>
     */
    public java.util.List<com.proto.common.KeyStringValuePair.Builder> 
         getDetailBuilderList() {
      return getDetailFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.proto.common.KeyStringValuePair, com.proto.common.KeyStringValuePair.Builder, com.proto.common.KeyStringValuePairOrBuilder> 
        getDetailFieldBuilder() {
      if (detailBuilder_ == null) {
        detailBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.proto.common.KeyStringValuePair, com.proto.common.KeyStringValuePair.Builder, com.proto.common.KeyStringValuePairOrBuilder>(
                detail_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        detail_ = null;
      }
      return detailBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:report.ReportData)
  }

  // @@protoc_insertion_point(class_scope:report.ReportData)
  private static final com.proto.report.ReportData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.proto.report.ReportData();
  }

  public static com.proto.report.ReportData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReportData>
      PARSER = new com.google.protobuf.AbstractParser<ReportData>() {
    @java.lang.Override
    public ReportData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ReportData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReportData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReportData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.proto.report.ReportData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

