// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: report.proto

package com.proto.report;

public final class Report {
  private Report() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_report_ReportData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_report_ReportData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014report.proto\022\006report\032\014common.proto\"`\n\n" +
      "ReportData\022&\n\nreportType\030\001 \001(\0162\022.report." +
      "ReportType\022*\n\006detail\030\002 \003(\0132\032.common.KeyS" +
      "tringValuePair*#\n\nReportType\022\n\n\006Normal\020\000" +
      "\022\t\n\005Error\020\0012\207\001\n\rReportService\0226\n\014uploadR" +
      "eport\022\022.report.ReportData\032\020.common.Comma" +
      "nds\"\000\022>\n\022uploadStreamReport\022\022.report.Rep" +
      "ortData\032\020.common.Commands\"\000(\001B\024\n\020com.pro" +
      "to.reportP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.proto.common.Common.getDescriptor(),
        }, assigner);
    internal_static_report_ReportData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_report_ReportData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_report_ReportData_descriptor,
        new java.lang.String[] { "ReportType", "Detail", });
    com.proto.common.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
